In [5]:
#reshape함수는 np.reshape(변경할 배열, 차원) 또는 배열.reshape(차원)으로

#사용 할 수 있으며, 현재의 배열의 차원(1차원,2차원,3차원)을

#변경하여 행렬을 반환하거나 하는 경우에 많이 이용되는 함수이다.


In [6]:
#1-1 <1차원과 2차원의 변환>

In [21]:
#차원은 대괄호의 개수로 알수도 있다.

import numpy as np
a = [1,2,3,4,5,6,7,8]
b = np.reshape(a,(2,4))
c = np.reshape(a,(4,2))
print(b)
print('\n')
print(c)

[[1 2 3 4]
 [5 6 7 8]]


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [22]:
#1-2 <3차원 반환>

In [27]:
a = np.arange(1,9)
#0번부터 인덱스 순서대로 값을 넣는다.
#np.arange() 는 일정 간격의 정수와 실수 배열을 만든다. 기본간격이 1

print(a)

[1 2 3 4 5 6 7 8]


In [33]:
b = np.arange(10)

print(b)

c = np.arange(2, 20, 3)

print(c)

[0 1 2 3 4 5 6 7 8 9]
[ 2  5  8 11 14 17]


In [34]:
d = np.arange(1,9)    #1부터 9까지 있음
e = a.reshape(2,2,2)
print(e)
print('-'*20)
e             #왜 array라고 뜰까? 배열이라서?

#다차원 배열을 처리하는 nd.array객체
#np.array = 리스트를 array로 바꾸는 함수임.

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
--------------------


array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [35]:
e[0] #3차원에서 첫 번째 행렬의 1행 2열 값 인덱싱

array([[1, 2],
       [3, 4]])

In [36]:
e[0][0,1] #3차원에서 첫 번째 행렬[0]의 1행 2열[0.1] 값 인덱싱

2

In [44]:
e[1][1,1]

8

In [45]:
e[1][1,0]

7

In [46]:
e[1][0,1]

6

In [ ]:
#reshape에서 -1의 의미

#입력인수로 -1이 들어간 경우가 종종 있음
#-1이 의미하는 바는, 변경된 배열의 -1 위치의 차원은
#원래 배열의 길이와 남은 차원으로 부터 추정이 된다는 뜻

In [52]:
x = np.arange(12)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [59]:
x = x.reshape(3,4) #3행 4열
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [54]:
#2-1 <reshape(-1, 정수):행의 위치에 -1 인 경우

In [60]:
x.reshape(-1,1) #행이 -되는 것이 아니라 아예 다 행을 만들어줌 12개

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [61]:
x.reshape(-1,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [62]:
x.reshape(-1,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
#즉 행의 위치에 -1을 넣고 열의 갚을 지정해주면 반환될
#배열의 행의 수는 알아서 지정이 된다는 소리이다.

In [ ]:
#2-2 <reshape(정수,-1):열의 위치에 -1인 경우

In [63]:
x.reshape(1,-1) #열이 12개가 되어버리네

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [64]:
x.reshape(2,-1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [65]:
x.reshape(3,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [66]:
x.reshape(4,-1)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
#이것도 마찬가지로, 행의 수를 지정해주면 열은 알아서 자동으로 재배열을 해주는 것

In [ ]:
#2-3 <reshape(-1)인 경우>

In [67]:
x.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [68]:
x.reshape(1,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [ ]:
#1만 들어가면 1차원 배열을 반환한다. 모양상 x.reshape(1,-1)과
#같으나 이는 (1,12)인 2차원 배열이다 !!대괄호 수로 확인 가능